### ISSUE TITLE
t/compilers/opsc/03-past.t CallContext GC assertion src/call/context.c:745

### ISSUE THREAD

**Issue by rurban** [parrot/parrot#1159]
On my centos5 i386 system with very low memory, 500MB, and also on jim's darwin/ppc system. see #1160.
One Object argument to a method call is already freed. `"parrot;NQP;Actions;quote:sym</ />"`
Very likely a Regex;Cursor object

Not repro with `./parrot_old -D101 -- ./parrot-nqp.pbc t/compilers/opsc/03-past.t` nor with `-t`,
but with `./parrot_old -D1 --gc-debug -- ./parrot-nqp.pbc t/compilers/opsc/03-past.t`

```
$ prove t/compilers/opsc/03-past.t
t/compilers/opsc/03-past....src/call/context.c:745: failed assertion '!*res || !PObj_on_free_list_TEST(*res)'
Backtrace - Obtained 21 stack frames (max trace depth is 32).
/usr/src/parrot/parrot/blib/lib/libparrot.so.6.10.0 [0x92967a]
/usr/src/parrot/parrot/blib/lib/libparrot.so.6.10.0(Parrot_confess+0x9a) [0x92982a]
/usr/src/parrot/parrot/blib/lib/libparrot.so.6.10.0(Parrot_pcc_get_PMC_reg+0x115) [0x94f085]
/usr/src/parrot/parrot/blib/lib/libparrot.so.6.10.0(Parrot_pcc_build_sig_object_from_op+0x45e) [0x94aefe]
/usr/src/parrot/parrot/blib/lib/libparrot.so.6.10.0 [0x916177]
/usr/src/parrot/parrot/blib/lib/libparrot.so.6.10.0 [0x976518]
/usr/src/parrot/parrot/blib/lib/libparrot.so.6.10.0 [0x975baa]
/usr/src/parrot/parrot/blib/lib/libparrot.so.6.10.0 [0x94e0ca]
/usr/src/parrot/parrot/blib/lib/libparrot.so.6.10.0(Parrot_pcc_invoke_from_sig_object+0x187) [0x947167]
/usr/src/parrot/parrot/blib/lib/libparrot.so.6.10.0(Parrot_ext_call+0x170) [0x92b890]
/usr/src/parrot/parrot/blib/lib/libparrot.so.6.10.0 [0xa7ed51]
/usr/src/parrot/parrot/blib/lib/libparrot.so.6.10.0(Parrot_pcc_invoke_from_sig_object+0x13c) [0x94711c]
/usr/src/parrot/parrot/blib/lib/libparrot.so.6.10.0(Parrot_ext_call+0x10b) [0x92b82b]
/usr/src/parrot/parrot/blib/lib/libparrot.so.6.10.0 [0x97d353]
/usr/src/parrot/parrot/blib/lib/libparrot.so.6.10.0 [0x97d3de]
/usr/src/parrot/parrot/blib/lib/libparrot.so.6.10.0(Parrot_cx_begin_execution+0x11b) [0x97d6ab]
/usr/src/parrot/parrot/blib/lib/libparrot.so.6.10.0(Parrot_pf_execute_bytecode_program+0x177) [0x98bea7]
/usr/src/parrot/parrot/blib/lib/libparrot.so.6.10.0(Parrot_api_run_bytecode+0x163) [0x923cb3]
./parrot-nqp(main+0x241) [0x8048f7f]
/lib/libc.so.6(__libc_start_main+0xdc) [0x5e3ebc]
./parrot-nqp [0x8048c81]
Attempting to get PIR backtrace.  No guarantees.  Here goes...
current instr.: 'parrot;NQP;Actions;quote:sym</ />' pc 90645 (ext/nqp-rx/src/stage0/NQP-s0.pir:27632)
called from Sub 'parrot;Regex;Cursor;!reduce' pc 1238 (ext/nqp-rx/src/stage0/Regex-s0.pir:744)
called from Sub 'parrot;Regex;Cursor;!cursor_pass' pc 692 (ext/nqp-rx/src/stage0/Regex-s0.pir:414)
called from Sub 'parrot;NQP;Grammar;quote:sym</ />' pc 45611 (ext/nqp-rx/src/stage0/NQP-s0.pir:12761)
called from Sub 'parrot;Regex;Cursor;!protoregex' pc 2520 (ext/nqp-rx/src/stage0/Regex-s0.pir:1295)
called from Sub 'parrot;NQP;Grammar;quote' pc 43329 (ext/nqp-rx/src/stage0/NQP-s0.pir:12087)
called from Sub 'parrot;NQP;Grammar;value' pc 42648 (ext/nqp-rx/src/stage0/NQP-s0.pir:11905)
called from Sub 'parrot;NQP;Grammar;term:sym<value>' pc 42361 (ext/nqp-rx/src/stage0/NQP-s0.pir:11819)
called from Sub 'parrot;Regex;Cursor;!protoregex' pc 2520 (ext/nqp-rx/src/stage0/Regex-s0.pir:1295)
called from Sub 'parrot;NQP;Grammar;term' pc 40076 (ext/nqp-rx/src/stage0/NQP-s0.pir:11148)
called from Sub 'parrot;HLL;Grammar;termish' pc 2977 (ext/nqp-rx/src/stage0/HLL-s0.pir:1297)
called from Sub 'parrot;HLL;Grammar;EXPR' pc 1228 (ext/nqp-rx/src/stage0/HLL-s0.pir:674)
called from Sub 'parrot;NQP;Grammar;arglist' pc 42086 (ext/nqp-rx/src/stage0/NQP-s0.pir:11733)
called from Sub 'parrot;NQP;Grammar;args' pc 41745 (ext/nqp-rx/src/stage0/NQP-s0.pir:11634)
called from Sub 'parrot;NQP;Grammar;term:sym<identifier>' pc 40630 (ext/nqp-rx/src/stage0/NQP-s0.pir:11317)
called from Sub 'parrot;Regex;Cursor;!protoregex' pc 2557 (ext/nqp-rx/src/stage0/Regex-s0.pir:1308)
called from Sub 'parrot;NQP;Grammar;term' pc 40076 (ext/nqp-rx/src/stage0/NQP-s0.pir:11148)
called from Sub 'parrot;HLL;Grammar;termish' pc 2977 (ext/nqp-rx/src/stage0/HLL-s0.pir:1297)
called from Sub 'parrot;HLL;Grammar;EXPR' pc 1228 (ext/nqp-rx/src/stage0/HLL-s0.pir:674)
called from Sub 'parrot;NQP;Grammar;statement' pc 7666 (ext/nqp-rx/src/stage0/NQP-s0.pir:2464)
called from Sub 'parrot;NQP;Grammar;statementlist' pc 7151 (ext/nqp-rx/src/stage0/NQP-s0.pir:2333)
called from Sub 'parrot;NQP;Grammar;comp_unit' pc 6694 (ext/nqp-rx/src/stage0/NQP-s0.pir:2207)
called from Sub 'parrot;NQP;Grammar;TOP' pc 1322 (ext/nqp-rx/src/stage0/NQP-s0.pir:528)
called from Sub 'parrot;Regex;Cursor;parse' pc 371 (ext/nqp-rx/src/stage0/Regex-s0.pir:230)
called from Sub 'parrot;HLL;Compiler;parse' pc 96 (ext/nqp-rx/src/stage0/HLL-s0.pir:63)
called from Sub 'parrot;PCT;HLLCompiler;compile' pc 459 (compilers/pct/src/PCT/HLLCompiler.pir:326)
called from Sub 'parrot;HLL;Compiler;eval' pc 24537 (ext/nqp-rx/src/stage0/HLL-s0.pir:8848)
called from Sub 'parrot;PCT;HLLCompiler;evalfiles' pc 1532 (compilers/pct/src/PCT/HLLCompiler.pir:768)
called from Sub 'parrot;PCT;HLLCompiler;command_line' pc 1757 (compilers/pct/src/PCT/HLLCompiler.pir:883)
called from Sub 'parrot;NQP;Compiler;main' pc 92462 (ext/nqp-rx/src/stage0/NQP-s0.pir:28374)

$ gdb --args ./parrot-nqp t/compilers/opsc/03-past.t
(gdb) f 4
#4  0x001e2085 in Parrot_pcc_get_PMC_reg (interp=0x80e4030, ctx=0x8d8b460, idx=8)
    at src/call/context.c:745
745	    PARROT_ASSERT(!*res || !PObj_on_free_list_TEST(*res));

2nd CallContext pmc arg
res: Object, PMC is on free list

(gdb) bt
#0  0x00110402 in __kernel_vsyscall ()
#1  0x005f6e30 in raise () from /lib/libc.so.6
#2  0x005f8741 in abort () from /lib/libc.so.6
#3  0x001bc82f in Parrot_confess (cond=0x353790 "!*res || !PObj_on_free_list_TEST(*res)", 
    file=0x353580 "src/call/context.c", line=745) at src/exceptions.c:647
#4  0x001e2085 in Parrot_pcc_get_PMC_reg (interp=0x80e4030, ctx=0x8d8b460, idx=8)
    at src/call/context.c:745
#5  0x001ddefe in Parrot_pcc_build_sig_object_from_op (interp=0x80e4030, signature=0x81394f8, 
    raw_sig=0x81836f0, raw_args=0xb73cc85c) at src/call/args.c:404
#6  0x001a9177 in Parrot_set_args_pc (cur_opcode=0xb73cc85c, interp=0x80e4030)
    at src/ops/core_ops.c:13965
#7  0x00209518 in runops_fast_core (interp=0x80e4030, runcore_unused=0x8179580, pc=0xb73cc85c)
    at src/runcore/cores.c:495
#8  0x00208baa in runops_int (interp=0x80e4030, offset=1063) at src/runcore/main.c:221
#9  0x001e10ca in runops (interp=0x80e4030, offs=1063) at src/call/ops.c:123
#10 0x001da167 in Parrot_pcc_invoke_from_sig_object (interp=0x80e4030, sub_obj=0x8421f70, 
    call_object=0x8421fc0) at src/call/pcc.c:340
#11 0x001be890 in Parrot_ext_call (interp=0x80e4030, sub_pmc=0x8421f70, signature=0x3953fc "P->")
    at src/extend.c:164
#12 0x00311d51 in Parrot_Task_invoke (interp=0x80e4030, _self=0x8409638, next=0x0)
    at ./src/pmc/task.pmc:175
#13 0x001da11c in Parrot_pcc_invoke_from_sig_object (interp=0x80e4030, sub_obj=0x8409638, 
    call_object=0x8421f84) at src/call/pcc.c:332
#14 0x001be82b in Parrot_ext_call (interp=0x80e4030, sub_pmc=0x8409638, signature=0x356233 "->")
    at src/extend.c:155
#15 0x00210353 in Parrot_cx_next_task (interp=0x80e4030, scheduler=0x81781a0) at src/scheduler.c:231
#16 0x002103de in Parrot_cx_outer_runloop (interp=0x80e4030) at src/scheduler.c:149

```

As it appears now also on jim's ppc macbook, it's clearly a regression.

**Comment by rurban** [comment]
Closing this one, as the new test passes and looks stable.
